mysql:
  dbname: "StuServiceDB"
  host: "127.0.0.1"
  port:
  user: root
  pass:
file:
  imagePath: "/static/image"
  imageExtension: [".jpg", ".jpeg", ".png"]
email:
  host: "smtp.qq.com"
  port: 25
  userName: ""
  password: ""
userType:
  student: 1
  admin: 2