mysql:
  dbname: "StuServiceDB"
  host:
  port:
  user: root
  pass:
redis:
  host: "localhost:6379"
  password: ""
  DB: 0
file:
  imagePath: "/static/image"
  imageExtension: [".jpg", ".jpeg", ".png"]
email:
  host: "smtp.qq.com"
  port: 25
  userName: ""
  password: ""
  verifyCodeExpireMinute: 5
userType:
  student: 1
  admin: 2
JWT:
  Secret: ""
  ExpireHour: 2
Security:
  LimitPerSec: 4